// Generated automatically by nearley, version 2.20.1
// http://github.com/Hardmath123/nearley
(function () {
function id(x) { return x[0]; }

function single_param(d) {
    return [ d[0], d[2] ]
}

function dip(d) {
    return [ d[0], d[4] ]
}

function dipi(d) {
    return [ d[0], d[2], d[6] ]
}

function code(d) {
    var rarr = [];
    for (var i = 0; i < d[4].length; i++) {
        rarr[i] = d[4][i];
    }
    return rarr;
}

function ifs(d) {
    return [d[0], d[4], d[10]];
}

function ins(d) {
    if (d[0].length == 1) {
        return d[0][0];
    } else {
        return d[0];
    }
}

var grammar = {
    Lexer: undefined,
    ParserRules: [
    {"name": "_$ebnf$1", "symbols": []},
    {"name": "_$ebnf$1", "symbols": ["_$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "_", "symbols": ["_$ebnf$1"], "postprocess": function(d) {return null;}},
    {"name": "__$ebnf$1", "symbols": ["wschar"]},
    {"name": "__$ebnf$1", "symbols": ["__$ebnf$1", "wschar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "__", "symbols": ["__$ebnf$1"], "postprocess": function(d) {return null;}},
    {"name": "wschar", "symbols": [/[ \t\n\v\f]/], "postprocess": id},
    {"name": "unsigned_int$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "unsigned_int$ebnf$1", "symbols": ["unsigned_int$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "unsigned_int", "symbols": ["unsigned_int$ebnf$1"], "postprocess": 
        function(d) {
            return parseInt(d[0].join(""));
        }
        },
    {"name": "int$ebnf$1$subexpression$1", "symbols": [{"literal":"-"}]},
    {"name": "int$ebnf$1$subexpression$1", "symbols": [{"literal":"+"}]},
    {"name": "int$ebnf$1", "symbols": ["int$ebnf$1$subexpression$1"], "postprocess": id},
    {"name": "int$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "int$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "int$ebnf$2", "symbols": ["int$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "int", "symbols": ["int$ebnf$1", "int$ebnf$2"], "postprocess": 
        function(d) {
            if (d[0]) {
                return parseInt(d[0][0]+d[1].join(""));
            } else {
                return parseInt(d[1].join(""));
            }
        }
        },
    {"name": "unsigned_decimal$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "unsigned_decimal$ebnf$1", "symbols": ["unsigned_decimal$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "unsigned_decimal$ebnf$2$subexpression$1$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "unsigned_decimal$ebnf$2$subexpression$1$ebnf$1", "symbols": ["unsigned_decimal$ebnf$2$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "unsigned_decimal$ebnf$2$subexpression$1", "symbols": [{"literal":"."}, "unsigned_decimal$ebnf$2$subexpression$1$ebnf$1"]},
    {"name": "unsigned_decimal$ebnf$2", "symbols": ["unsigned_decimal$ebnf$2$subexpression$1"], "postprocess": id},
    {"name": "unsigned_decimal$ebnf$2", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "unsigned_decimal", "symbols": ["unsigned_decimal$ebnf$1", "unsigned_decimal$ebnf$2"], "postprocess": 
        function(d) {
            return parseFloat(
                d[0].join("") +
                (d[1] ? "."+d[1][1].join("") : "")
            );
        }
        },
    {"name": "decimal$ebnf$1", "symbols": [{"literal":"-"}], "postprocess": id},
    {"name": "decimal$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decimal$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "decimal$ebnf$2", "symbols": ["decimal$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decimal$ebnf$3$subexpression$1$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "decimal$ebnf$3$subexpression$1$ebnf$1", "symbols": ["decimal$ebnf$3$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "decimal$ebnf$3$subexpression$1", "symbols": [{"literal":"."}, "decimal$ebnf$3$subexpression$1$ebnf$1"]},
    {"name": "decimal$ebnf$3", "symbols": ["decimal$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "decimal$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "decimal", "symbols": ["decimal$ebnf$1", "decimal$ebnf$2", "decimal$ebnf$3"], "postprocess": 
        function(d) {
            return parseFloat(
                (d[0] || "") +
                d[1].join("") +
                (d[2] ? "."+d[2][1].join("") : "")
            );
        }
        },
    {"name": "percentage", "symbols": ["decimal", {"literal":"%"}], "postprocess": 
        function(d) {
            return d[0]/100;
        }
        },
    {"name": "jsonfloat$ebnf$1", "symbols": [{"literal":"-"}], "postprocess": id},
    {"name": "jsonfloat$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "jsonfloat$ebnf$2", "symbols": ["jsonfloat$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "jsonfloat$ebnf$3$subexpression$1$ebnf$1", "symbols": [/[0-9]/]},
    {"name": "jsonfloat$ebnf$3$subexpression$1$ebnf$1", "symbols": ["jsonfloat$ebnf$3$subexpression$1$ebnf$1", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "jsonfloat$ebnf$3$subexpression$1", "symbols": [{"literal":"."}, "jsonfloat$ebnf$3$subexpression$1$ebnf$1"]},
    {"name": "jsonfloat$ebnf$3", "symbols": ["jsonfloat$ebnf$3$subexpression$1"], "postprocess": id},
    {"name": "jsonfloat$ebnf$3", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$1", "symbols": [/[+-]/], "postprocess": id},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$1", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$2", "symbols": [/[0-9]/]},
    {"name": "jsonfloat$ebnf$4$subexpression$1$ebnf$2", "symbols": ["jsonfloat$ebnf$4$subexpression$1$ebnf$2", /[0-9]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "jsonfloat$ebnf$4$subexpression$1", "symbols": [/[eE]/, "jsonfloat$ebnf$4$subexpression$1$ebnf$1", "jsonfloat$ebnf$4$subexpression$1$ebnf$2"]},
    {"name": "jsonfloat$ebnf$4", "symbols": ["jsonfloat$ebnf$4$subexpression$1"], "postprocess": id},
    {"name": "jsonfloat$ebnf$4", "symbols": [], "postprocess": function(d) {return null;}},
    {"name": "jsonfloat", "symbols": ["jsonfloat$ebnf$1", "jsonfloat$ebnf$2", "jsonfloat$ebnf$3", "jsonfloat$ebnf$4"], "postprocess": 
        function(d) {
            return parseFloat(
                (d[0] || "") +
                d[1].join("") +
                (d[2] ? "."+d[2][1].join("") : "") +
                (d[3] ? "e" + (d[3][1] || "+") + d[3][2].join("") : "")
            );
        }
        },
    {"name": "dqstring$ebnf$1", "symbols": []},
    {"name": "dqstring$ebnf$1", "symbols": ["dqstring$ebnf$1", "dstrchar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "dqstring", "symbols": [{"literal":"\""}, "dqstring$ebnf$1", {"literal":"\""}], "postprocess": function(d) {return d[1].join(""); }},
    {"name": "sqstring$ebnf$1", "symbols": []},
    {"name": "sqstring$ebnf$1", "symbols": ["sqstring$ebnf$1", "sstrchar"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "sqstring", "symbols": [{"literal":"'"}, "sqstring$ebnf$1", {"literal":"'"}], "postprocess": function(d) {return d[1].join(""); }},
    {"name": "btstring$ebnf$1", "symbols": []},
    {"name": "btstring$ebnf$1", "symbols": ["btstring$ebnf$1", /[^`]/], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "btstring", "symbols": [{"literal":"`"}, "btstring$ebnf$1", {"literal":"`"}], "postprocess": function(d) {return d[1].join(""); }},
    {"name": "dstrchar", "symbols": [/[^\\"\n]/], "postprocess": id},
    {"name": "dstrchar", "symbols": [{"literal":"\\"}, "strescape"], "postprocess": 
        function(d) {
            return JSON.parse("\""+d.join("")+"\"");
        }
        },
    {"name": "sstrchar", "symbols": [/[^\\'\n]/], "postprocess": id},
    {"name": "sstrchar", "symbols": [{"literal":"\\"}, "strescape"], "postprocess": function(d) { return JSON.parse("\""+d.join("")+"\""); }},
    {"name": "sstrchar$string$1", "symbols": [{"literal":"\\"}, {"literal":"'"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "sstrchar", "symbols": ["sstrchar$string$1"], "postprocess": function(d) {return "'"; }},
    {"name": "strescape", "symbols": [/["\\/bfnrt]/], "postprocess": id},
    {"name": "strescape", "symbols": [{"literal":"u"}, /[a-fA-F0-9]/, /[a-fA-F0-9]/, /[a-fA-F0-9]/, /[a-fA-F0-9]/], "postprocess": 
        function(d) {
            return d.join("");
        }
        },
    {"name": "main", "symbols": ["parameter", "_", "storage", "_", "code", "_"], "postprocess": function(d) { return JSON.stringify({"parameter": d[0], "storage": d[2], "code": d[4]}) }},
    {"name": "parameter$string$1", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "parameter", "symbols": ["parameter$string$1", "__", "type", "_", {"literal":";"}], "postprocess": function(d) { return d[2] }},
    {"name": "storage$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "storage", "symbols": ["storage$string$1", "__", "type", "_", {"literal":";"}], "postprocess": function(d) { return d[2] }},
    {"name": "code$string$1", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "code$ebnf$1", "symbols": []},
    {"name": "code$ebnf$1", "symbols": ["code$ebnf$1", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "code", "symbols": ["code$string$1", "_", {"literal":"{"}, "_", "code$ebnf$1", {"literal":"}"}, "_", {"literal":";"}], "postprocess": code},
    {"name": "ins", "symbols": ["instruction", "_", {"literal":";"}, "_"], "postprocess": ins},
    {"name": "type$string$1", "symbols": [{"literal":"a"}, {"literal":"d"}, {"literal":"d"}, {"literal":"r"}, {"literal":"e"}, {"literal":"s"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$1"], "postprocess": function(d) { return 'address' }},
    {"name": "type$string$2", "symbols": [{"literal":"b"}, {"literal":"i"}, {"literal":"g"}, {"literal":"_"}, {"literal":"m"}, {"literal":"a"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": [{"literal":"("}, "_", "type$string$2", "__", "type", "__", "type", "_", {"literal":")"}], "postprocess": function(d) { return [ "big_map", [ [ d[4][0], d[6][0] ] ] ] }},
    {"name": "type$string$3", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"s"}, {"literal":"1"}, {"literal":"2"}, {"literal":"_"}, {"literal":"3"}, {"literal":"8"}, {"literal":"1"}, {"literal":"_"}, {"literal":"f"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$3"], "postprocess": function(d) { return 'bls12_381_fr' }},
    {"name": "type$string$4", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"s"}, {"literal":"1"}, {"literal":"2"}, {"literal":"_"}, {"literal":"3"}, {"literal":"8"}, {"literal":"1"}, {"literal":"_"}, {"literal":"g"}, {"literal":"1"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$4"], "postprocess": function(d) { return 'bls12_381_g1' }},
    {"name": "type$string$5", "symbols": [{"literal":"b"}, {"literal":"l"}, {"literal":"s"}, {"literal":"1"}, {"literal":"2"}, {"literal":"_"}, {"literal":"3"}, {"literal":"8"}, {"literal":"1"}, {"literal":"_"}, {"literal":"g"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$5"], "postprocess": function(d) { return 'bls12_381_g2' }},
    {"name": "type$string$6", "symbols": [{"literal":"b"}, {"literal":"o"}, {"literal":"o"}, {"literal":"l"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$6"], "postprocess": function(d) { return 'bool' }},
    {"name": "type$string$7", "symbols": [{"literal":"b"}, {"literal":"y"}, {"literal":"t"}, {"literal":"e"}, {"literal":"s"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$7"], "postprocess": function(d) { return 'bytes' }},
    {"name": "type$string$8", "symbols": [{"literal":"c"}, {"literal":"h"}, {"literal":"a"}, {"literal":"i"}, {"literal":"n"}, {"literal":"_"}, {"literal":"i"}, {"literal":"d"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$8"], "postprocess": function(d) { return 'chain_id' }},
    {"name": "type$string$9", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"n"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$9", "__", "type"], "postprocess": function(d) { return { 'contract': d[2][0] } }},
    {"name": "type$string$10", "symbols": [{"literal":"i"}, {"literal":"n"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$10"], "postprocess": function(d) { return 'int' }},
    {"name": "type$string$11", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$11"], "postprocess": function(d) { return 'key' }},
    {"name": "type$string$12", "symbols": [{"literal":"k"}, {"literal":"e"}, {"literal":"y"}, {"literal":"_"}, {"literal":"h"}, {"literal":"a"}, {"literal":"s"}, {"literal":"h"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$12"], "postprocess": function(d) { return 'key_hash' }},
    {"name": "type$string$13", "symbols": [{"literal":"l"}, {"literal":"a"}, {"literal":"m"}, {"literal":"b"}, {"literal":"d"}, {"literal":"a"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$13"], "postprocess": function(d) { return 'lambda' }},
    {"name": "type$string$14", "symbols": [{"literal":"l"}, {"literal":"i"}, {"literal":"s"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$14", "__", "type"], "postprocess": function(d) { return [ "list", [ [ d[4][0], d[6][0] ] ] ] }},
    {"name": "type$string$15", "symbols": [{"literal":"m"}, {"literal":"a"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$15", "__", "type", "__", "type"], "postprocess": function(d) { return [ "map", [ [ d[4][0], d[6][0] ] ] ] }},
    {"name": "type$string$16", "symbols": [{"literal":"m"}, {"literal":"u"}, {"literal":"t"}, {"literal":"e"}, {"literal":"z"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$16"], "postprocess": function(d) { return 'mutez' }},
    {"name": "type$string$17", "symbols": [{"literal":"n"}, {"literal":"a"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$17"], "postprocess": function(d) { return 'nat' }},
    {"name": "type$string$18", "symbols": [{"literal":"n"}, {"literal":"e"}, {"literal":"v"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$18"], "postprocess": function(d) { return 'never' }},
    {"name": "type$string$19", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"e"}, {"literal":"r"}, {"literal":"a"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$19"], "postprocess": function(d) { return 'operation' }},
    {"name": "type$string$20", "symbols": [{"literal":"o"}, {"literal":"p"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$20", "__", "type"], "postprocess": function(d) { return { 'option': d[2][0] } }},
    {"name": "type$string$21", "symbols": [{"literal":"o"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": [{"literal":"("}, "_", "type$string$21", "__", "type", "__", "type", "_", {"literal":")"}], "postprocess": function(d) { return [ "or", [ [ d[4][0], d[6][0] ] ] ] }},
    {"name": "type$string$22", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"i"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": [{"literal":"("}, "_", "type$string$22", "__", "type", "__", "type", "_", {"literal":")"}], "postprocess": function(d) { return [ "pair", [ [ d[4][0], d[6][0] ] ] ] }},
    {"name": "type$string$23", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"_"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"t"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$23", "__", "type"], "postprocess": function(d) { return { 'sapling_state': d[2][0] } }},
    {"name": "type$string$24", "symbols": [{"literal":"s"}, {"literal":"a"}, {"literal":"p"}, {"literal":"l"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}, {"literal":"_"}, {"literal":"t"}, {"literal":"r"}, {"literal":"a"}, {"literal":"n"}, {"literal":"s"}, {"literal":"a"}, {"literal":"c"}, {"literal":"t"}, {"literal":"i"}, {"literal":"o"}, {"literal":"n"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$24", "__", "type"], "postprocess": function(d) { return { 'sapling_transaction': d[2][0] } }},
    {"name": "type$string$25", "symbols": [{"literal":"s"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$25", "__", "type"], "postprocess": function(d) { return { 'set': d[2][0] } }},
    {"name": "type$string$26", "symbols": [{"literal":"s"}, {"literal":"i"}, {"literal":"g"}, {"literal":"n"}, {"literal":"a"}, {"literal":"t"}, {"literal":"u"}, {"literal":"r"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$26"], "postprocess": function(d) { return 'signature' }},
    {"name": "type$string$27", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$27"], "postprocess": function(d) { return 'string' }},
    {"name": "type$string$28", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"c"}, {"literal":"k"}, {"literal":"e"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$28", "__", "type"], "postprocess": function(d) { return { 'ticket': d[2][0] } }},
    {"name": "type$string$29", "symbols": [{"literal":"t"}, {"literal":"i"}, {"literal":"m"}, {"literal":"e"}, {"literal":"s"}, {"literal":"t"}, {"literal":"a"}, {"literal":"m"}, {"literal":"p"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$29"], "postprocess": function(d) { return 'timestamp' }},
    {"name": "type$string$30", "symbols": [{"literal":"u"}, {"literal":"n"}, {"literal":"i"}, {"literal":"t"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "type", "symbols": ["type$string$30"], "postprocess": function(d) { return 'unit' }},
    {"name": "instruction$string$1", "symbols": [{"literal":"A"}, {"literal":"B"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$1"]},
    {"name": "instruction$string$2", "symbols": [{"literal":"A"}, {"literal":"D"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$2"]},
    {"name": "instruction$string$3", "symbols": [{"literal":"A"}, {"literal":"D"}, {"literal":"D"}, {"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$3"]},
    {"name": "instruction$string$4", "symbols": [{"literal":"A"}, {"literal":"M"}, {"literal":"O"}, {"literal":"U"}, {"literal":"N"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$4"]},
    {"name": "instruction$string$5", "symbols": [{"literal":"A"}, {"literal":"N"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$5"]},
    {"name": "instruction$string$6", "symbols": [{"literal":"A"}, {"literal":"P"}, {"literal":"P"}, {"literal":"L"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$6"]},
    {"name": "instruction$string$7", "symbols": [{"literal":"B"}, {"literal":"A"}, {"literal":"L"}, {"literal":"A"}, {"literal":"N"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$7"]},
    {"name": "instruction$string$8", "symbols": [{"literal":"B"}, {"literal":"L"}, {"literal":"A"}, {"literal":"K"}, {"literal":"E"}, {"literal":"2"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$8"]},
    {"name": "instruction$string$9", "symbols": [{"literal":"C"}, {"literal":"A"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$9"]},
    {"name": "instruction$string$10", "symbols": [{"literal":"C"}, {"literal":"D"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$10"]},
    {"name": "instruction$string$11", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"A"}, {"literal":"I"}, {"literal":"N"}, {"literal":"_"}, {"literal":"I"}, {"literal":"D"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$11"]},
    {"name": "instruction$string$12", "symbols": [{"literal":"C"}, {"literal":"H"}, {"literal":"E"}, {"literal":"C"}, {"literal":"K"}, {"literal":"_"}, {"literal":"S"}, {"literal":"I"}, {"literal":"G"}, {"literal":"N"}, {"literal":"A"}, {"literal":"T"}, {"literal":"U"}, {"literal":"R"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$12"]},
    {"name": "instruction$string$13", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"M"}, {"literal":"P"}, {"literal":"A"}, {"literal":"R"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$13"]},
    {"name": "instruction$string$14", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"C"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$14"]},
    {"name": "instruction$string$15", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$15"]},
    {"name": "instruction$string$16", "symbols": [{"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"T"}, {"literal":"R"}, {"literal":"A"}, {"literal":"C"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$16", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$17", "symbols": [{"literal":"C"}, {"literal":"R"}, {"literal":"E"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}, {"literal":"_"}, {"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"T"}, {"literal":"R"}, {"literal":"A"}, {"literal":"C"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$string$18", "symbols": [{"literal":"p"}, {"literal":"a"}, {"literal":"r"}, {"literal":"a"}, {"literal":"m"}, {"literal":"e"}, {"literal":"t"}, {"literal":"e"}, {"literal":"r"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$string$19", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"o"}, {"literal":"r"}, {"literal":"a"}, {"literal":"g"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$string$20", "symbols": [{"literal":"c"}, {"literal":"o"}, {"literal":"d"}, {"literal":"e"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$17", "__", {"literal":"{"}, "_", "instruction$string$18", "__", "type", "_", {"literal":";"}, "_", "instruction$string$19", "__", "type", "_", {"literal":";"}, "_", "instruction$string$20", "__", "instruction", "_", {"literal":"}"}]},
    {"name": "instruction$string$21", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$21", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$22", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$22", "_", {"literal":"{"}, "_", "ins", {"literal":"}"}], "postprocess": dip},
    {"name": "instruction$string$23", "symbols": [{"literal":"D"}, {"literal":"I"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$23", "__", "int", "__", {"literal":"{"}, "_", "ins", {"literal":"}"}], "postprocess": dipi},
    {"name": "instruction$string$24", "symbols": [{"literal":"D"}, {"literal":"R"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$24"]},
    {"name": "instruction$string$25", "symbols": [{"literal":"D"}, {"literal":"R"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$25", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$26", "symbols": [{"literal":"D"}, {"literal":"U"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$26", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$27", "symbols": [{"literal":"D"}, {"literal":"U"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$27"]},
    {"name": "instruction$string$28", "symbols": [{"literal":"D"}, {"literal":"U"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$28", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$29", "symbols": [{"literal":"E"}, {"literal":"D"}, {"literal":"I"}, {"literal":"V"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$29"]},
    {"name": "instruction$string$30", "symbols": [{"literal":"E"}, {"literal":"M"}, {"literal":"P"}, {"literal":"T"}, {"literal":"Y"}, {"literal":"_"}, {"literal":"B"}, {"literal":"I"}, {"literal":"G"}, {"literal":"_"}, {"literal":"M"}, {"literal":"A"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$30", "__", "type", "__", "type"]},
    {"name": "instruction$string$31", "symbols": [{"literal":"E"}, {"literal":"M"}, {"literal":"P"}, {"literal":"T"}, {"literal":"Y"}, {"literal":"_"}, {"literal":"M"}, {"literal":"A"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$31", "__", "type", "__", "type"]},
    {"name": "instruction$string$32", "symbols": [{"literal":"E"}, {"literal":"M"}, {"literal":"P"}, {"literal":"T"}, {"literal":"Y"}, {"literal":"_"}, {"literal":"S"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$32", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$33", "symbols": [{"literal":"E"}, {"literal":"Q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$33"]},
    {"name": "instruction$string$34", "symbols": [{"literal":"E"}, {"literal":"X"}, {"literal":"E"}, {"literal":"C"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$34"]},
    {"name": "instruction$string$35", "symbols": [{"literal":"F"}, {"literal":"A"}, {"literal":"I"}, {"literal":"L"}, {"literal":"W"}, {"literal":"I"}, {"literal":"T"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$35"]},
    {"name": "instruction$string$36", "symbols": [{"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$36"]},
    {"name": "instruction$string$37", "symbols": [{"literal":"G"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$37"]},
    {"name": "instruction$string$38", "symbols": [{"literal":"G"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$38", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$39", "symbols": [{"literal":"G"}, {"literal":"E"}, {"literal":"T"}, {"literal":"_"}, {"literal":"A"}, {"literal":"N"}, {"literal":"D"}, {"literal":"_"}, {"literal":"U"}, {"literal":"P"}, {"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$39"]},
    {"name": "instruction$string$40", "symbols": [{"literal":"G"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$40"]},
    {"name": "instruction$string$41", "symbols": [{"literal":"H"}, {"literal":"A"}, {"literal":"S"}, {"literal":"H"}, {"literal":"_"}, {"literal":"K"}, {"literal":"E"}, {"literal":"Y"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$41"]},
    {"name": "instruction$string$42", "symbols": [{"literal":"I"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$1", "symbols": []},
    {"name": "instruction$ebnf$1", "symbols": ["instruction$ebnf$1", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$2", "symbols": []},
    {"name": "instruction$ebnf$2", "symbols": ["instruction$ebnf$2", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$42", "_", {"literal":"{"}, "_", "instruction$ebnf$1", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$2", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$43", "symbols": [{"literal":"I"}, {"literal":"F"}, {"literal":"_"}, {"literal":"C"}, {"literal":"O"}, {"literal":"N"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$3", "symbols": []},
    {"name": "instruction$ebnf$3", "symbols": ["instruction$ebnf$3", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$4", "symbols": []},
    {"name": "instruction$ebnf$4", "symbols": ["instruction$ebnf$4", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$43", "_", {"literal":"{"}, "_", "instruction$ebnf$3", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$4", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$44", "symbols": [{"literal":"I"}, {"literal":"F"}, {"literal":"_"}, {"literal":"L"}, {"literal":"E"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$5", "symbols": []},
    {"name": "instruction$ebnf$5", "symbols": ["instruction$ebnf$5", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$6", "symbols": []},
    {"name": "instruction$ebnf$6", "symbols": ["instruction$ebnf$6", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$44", "_", {"literal":"{"}, "_", "instruction$ebnf$5", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$6", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$45", "symbols": [{"literal":"I"}, {"literal":"F"}, {"literal":"_"}, {"literal":"N"}, {"literal":"O"}, {"literal":"N"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$7", "symbols": []},
    {"name": "instruction$ebnf$7", "symbols": ["instruction$ebnf$7", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$8", "symbols": []},
    {"name": "instruction$ebnf$8", "symbols": ["instruction$ebnf$8", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$45", "_", {"literal":"{"}, "_", "instruction$ebnf$7", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$8", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$46", "symbols": [{"literal":"I"}, {"literal":"F"}, {"literal":"_"}, {"literal":"S"}, {"literal":"O"}, {"literal":"M"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$9", "symbols": []},
    {"name": "instruction$ebnf$9", "symbols": ["instruction$ebnf$9", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$10", "symbols": []},
    {"name": "instruction$ebnf$10", "symbols": ["instruction$ebnf$10", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$46", "_", {"literal":"{"}, "_", "instruction$ebnf$9", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$10", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$47", "symbols": [{"literal":"I"}, {"literal":"F"}, {"literal":"C"}, {"literal":"M"}, {"literal":"P"}, {"literal":"G"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$11", "symbols": []},
    {"name": "instruction$ebnf$11", "symbols": ["instruction$ebnf$11", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$12", "symbols": []},
    {"name": "instruction$ebnf$12", "symbols": ["instruction$ebnf$12", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$47", "_", {"literal":"{"}, "_", "instruction$ebnf$11", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$12", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$48", "symbols": [{"literal":"I"}, {"literal":"F"}, {"literal":"C"}, {"literal":"M"}, {"literal":"P"}, {"literal":"G"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$13", "symbols": []},
    {"name": "instruction$ebnf$13", "symbols": ["instruction$ebnf$13", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$14", "symbols": []},
    {"name": "instruction$ebnf$14", "symbols": ["instruction$ebnf$14", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$48", "_", {"literal":"{"}, "_", "instruction$ebnf$13", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$14", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$49", "symbols": [{"literal":"I"}, {"literal":"F"}, {"literal":"C"}, {"literal":"M"}, {"literal":"P"}, {"literal":"L"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction$ebnf$15", "symbols": []},
    {"name": "instruction$ebnf$15", "symbols": ["instruction$ebnf$15", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction$ebnf$16", "symbols": []},
    {"name": "instruction$ebnf$16", "symbols": ["instruction$ebnf$16", "ins"], "postprocess": function arrpush(d) {return d[0].concat([d[1]]);}},
    {"name": "instruction", "symbols": ["instruction$string$49", "_", {"literal":"{"}, "_", "instruction$ebnf$15", "_", {"literal":"}"}, "_", {"literal":"{"}, "_", "instruction$ebnf$16", "_", {"literal":"}"}], "postprocess": ifs},
    {"name": "instruction$string$50", "symbols": [{"literal":"I"}, {"literal":"M"}, {"literal":"P"}, {"literal":"L"}, {"literal":"I"}, {"literal":"C"}, {"literal":"I"}, {"literal":"T"}, {"literal":"_"}, {"literal":"A"}, {"literal":"C"}, {"literal":"C"}, {"literal":"O"}, {"literal":"U"}, {"literal":"N"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$50"]},
    {"name": "instruction$string$51", "symbols": [{"literal":"I"}, {"literal":"N"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$51"]},
    {"name": "instruction$string$52", "symbols": [{"literal":"I"}, {"literal":"S"}, {"literal":"N"}, {"literal":"A"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$52"]},
    {"name": "instruction$string$53", "symbols": [{"literal":"I"}, {"literal":"T"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$53", "__", "instruction"], "postprocess": single_param},
    {"name": "instruction$string$54", "symbols": [{"literal":"J"}, {"literal":"O"}, {"literal":"I"}, {"literal":"N"}, {"literal":"_"}, {"literal":"T"}, {"literal":"I"}, {"literal":"C"}, {"literal":"K"}, {"literal":"E"}, {"literal":"T"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$54"]},
    {"name": "instruction$string$55", "symbols": [{"literal":"K"}, {"literal":"E"}, {"literal":"C"}, {"literal":"C"}, {"literal":"A"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$55"]},
    {"name": "instruction$string$56", "symbols": [{"literal":"L"}, {"literal":"A"}, {"literal":"M"}, {"literal":"B"}, {"literal":"D"}, {"literal":"A"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$56", "__", "type", "__", "type", "__", "instruction"]},
    {"name": "instruction$string$57", "symbols": [{"literal":"L"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$57"]},
    {"name": "instruction$string$58", "symbols": [{"literal":"L"}, {"literal":"E"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$58", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$59", "symbols": [{"literal":"L"}, {"literal":"E"}, {"literal":"V"}, {"literal":"E"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$59"]},
    {"name": "instruction$string$60", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"O"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$60", "__", "instruction"], "postprocess": single_param},
    {"name": "instruction$string$61", "symbols": [{"literal":"L"}, {"literal":"O"}, {"literal":"O"}, {"literal":"P"}, {"literal":"_"}, {"literal":"L"}, {"literal":"E"}, {"literal":"F"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$61", "__", "instruction"], "postprocess": single_param},
    {"name": "instruction$string$62", "symbols": [{"literal":"L"}, {"literal":"S"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$62"]},
    {"name": "instruction$string$63", "symbols": [{"literal":"L"}, {"literal":"S"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$63"]},
    {"name": "instruction$string$64", "symbols": [{"literal":"L"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$64"]},
    {"name": "instruction$string$65", "symbols": [{"literal":"M"}, {"literal":"A"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$65", "__", "instruction"], "postprocess": single_param},
    {"name": "instruction$string$66", "symbols": [{"literal":"M"}, {"literal":"E"}, {"literal":"M"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$66"]},
    {"name": "instruction$string$67", "symbols": [{"literal":"M"}, {"literal":"U"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$67"]},
    {"name": "instruction$string$68", "symbols": [{"literal":"N"}, {"literal":"E"}, {"literal":"G"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$68"]},
    {"name": "instruction$string$69", "symbols": [{"literal":"N"}, {"literal":"E"}, {"literal":"Q"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$69"]},
    {"name": "instruction$string$70", "symbols": [{"literal":"N"}, {"literal":"E"}, {"literal":"V"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$70"]},
    {"name": "instruction$string$71", "symbols": [{"literal":"N"}, {"literal":"I"}, {"literal":"L"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$71", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$72", "symbols": [{"literal":"N"}, {"literal":"O"}, {"literal":"N"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$72", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$73", "symbols": [{"literal":"N"}, {"literal":"O"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$73"]},
    {"name": "instruction$string$74", "symbols": [{"literal":"N"}, {"literal":"O"}, {"literal":"W"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$74"]},
    {"name": "instruction$string$75", "symbols": [{"literal":"O"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$75"]},
    {"name": "instruction$string$76", "symbols": [{"literal":"P"}, {"literal":"A"}, {"literal":"C"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$76"]},
    {"name": "instruction$string$77", "symbols": [{"literal":"P"}, {"literal":"A"}, {"literal":"I"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$77"]},
    {"name": "instruction$string$78", "symbols": [{"literal":"P"}, {"literal":"A"}, {"literal":"I"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$78", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$79", "symbols": [{"literal":"P"}, {"literal":"A"}, {"literal":"I"}, {"literal":"R"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}, {"literal":"_"}, {"literal":"C"}, {"literal":"H"}, {"literal":"E"}, {"literal":"C"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$79"]},
    {"name": "instruction$string$80", "symbols": [{"literal":"P"}, {"literal":"U"}, {"literal":"S"}, {"literal":"H"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$80", "__", "pushh"], "postprocess": single_param},
    {"name": "instruction$string$81", "symbols": [{"literal":"R"}, {"literal":"E"}, {"literal":"A"}, {"literal":"D"}, {"literal":"_"}, {"literal":"T"}, {"literal":"I"}, {"literal":"C"}, {"literal":"K"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$81"]},
    {"name": "instruction$string$82", "symbols": [{"literal":"R"}, {"literal":"I"}, {"literal":"G"}, {"literal":"H"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$82", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$83", "symbols": [{"literal":"S"}, {"literal":"A"}, {"literal":"P"}, {"literal":"L"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}, {"literal":"_"}, {"literal":"E"}, {"literal":"M"}, {"literal":"P"}, {"literal":"T"}, {"literal":"Y"}, {"literal":"_"}, {"literal":"S"}, {"literal":"T"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$83", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$84", "symbols": [{"literal":"S"}, {"literal":"A"}, {"literal":"P"}, {"literal":"L"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}, {"literal":"_"}, {"literal":"V"}, {"literal":"E"}, {"literal":"R"}, {"literal":"I"}, {"literal":"F"}, {"literal":"Y"}, {"literal":"_"}, {"literal":"U"}, {"literal":"P"}, {"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$84"]},
    {"name": "instruction$string$85", "symbols": [{"literal":"S"}, {"literal":"E"}, {"literal":"L"}, {"literal":"F"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$85"]},
    {"name": "instruction$string$86", "symbols": [{"literal":"S"}, {"literal":"E"}, {"literal":"L"}, {"literal":"F"}, {"literal":"_"}, {"literal":"A"}, {"literal":"D"}, {"literal":"D"}, {"literal":"R"}, {"literal":"E"}, {"literal":"S"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$86"]},
    {"name": "instruction$string$87", "symbols": [{"literal":"S"}, {"literal":"E"}, {"literal":"N"}, {"literal":"D"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$87"]},
    {"name": "instruction$string$88", "symbols": [{"literal":"S"}, {"literal":"E"}, {"literal":"T"}, {"literal":"_"}, {"literal":"D"}, {"literal":"E"}, {"literal":"L"}, {"literal":"E"}, {"literal":"G"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$88"]},
    {"name": "instruction$string$89", "symbols": [{"literal":"S"}, {"literal":"H"}, {"literal":"A"}, {"literal":"2"}, {"literal":"5"}, {"literal":"6"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$89"]},
    {"name": "instruction$string$90", "symbols": [{"literal":"S"}, {"literal":"H"}, {"literal":"A"}, {"literal":"3"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$90"]},
    {"name": "instruction$string$91", "symbols": [{"literal":"S"}, {"literal":"H"}, {"literal":"A"}, {"literal":"5"}, {"literal":"1"}, {"literal":"2"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$91"]},
    {"name": "instruction$string$92", "symbols": [{"literal":"S"}, {"literal":"I"}, {"literal":"Z"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$92"]},
    {"name": "instruction$string$93", "symbols": [{"literal":"S"}, {"literal":"L"}, {"literal":"I"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$93"]},
    {"name": "instruction$string$94", "symbols": [{"literal":"S"}, {"literal":"O"}, {"literal":"M"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$94"]},
    {"name": "instruction$string$95", "symbols": [{"literal":"S"}, {"literal":"O"}, {"literal":"U"}, {"literal":"R"}, {"literal":"C"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$95"]},
    {"name": "instruction$string$96", "symbols": [{"literal":"S"}, {"literal":"P"}, {"literal":"L"}, {"literal":"I"}, {"literal":"T"}, {"literal":"_"}, {"literal":"T"}, {"literal":"I"}, {"literal":"C"}, {"literal":"K"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$96"]},
    {"name": "instruction$string$97", "symbols": [{"literal":"S"}, {"literal":"U"}, {"literal":"B"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$97"]},
    {"name": "instruction$string$98", "symbols": [{"literal":"S"}, {"literal":"W"}, {"literal":"A"}, {"literal":"P"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$98"]},
    {"name": "instruction$string$99", "symbols": [{"literal":"T"}, {"literal":"I"}, {"literal":"C"}, {"literal":"K"}, {"literal":"E"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$99"]},
    {"name": "instruction$string$100", "symbols": [{"literal":"T"}, {"literal":"O"}, {"literal":"T"}, {"literal":"A"}, {"literal":"L"}, {"literal":"_"}, {"literal":"V"}, {"literal":"O"}, {"literal":"T"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}, {"literal":"_"}, {"literal":"P"}, {"literal":"O"}, {"literal":"W"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$100"]},
    {"name": "instruction$string$101", "symbols": [{"literal":"T"}, {"literal":"R"}, {"literal":"A"}, {"literal":"N"}, {"literal":"S"}, {"literal":"F"}, {"literal":"E"}, {"literal":"R"}, {"literal":"_"}, {"literal":"T"}, {"literal":"O"}, {"literal":"K"}, {"literal":"E"}, {"literal":"N"}, {"literal":"S"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$101"]},
    {"name": "instruction$string$102", "symbols": [{"literal":"U"}, {"literal":"N"}, {"literal":"I"}, {"literal":"T"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$102"]},
    {"name": "instruction$string$103", "symbols": [{"literal":"U"}, {"literal":"N"}, {"literal":"P"}, {"literal":"A"}, {"literal":"C"}, {"literal":"K"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$103", "__", "type"], "postprocess": single_param},
    {"name": "instruction$string$104", "symbols": [{"literal":"U"}, {"literal":"N"}, {"literal":"P"}, {"literal":"A"}, {"literal":"I"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$104"]},
    {"name": "instruction$string$105", "symbols": [{"literal":"U"}, {"literal":"N"}, {"literal":"P"}, {"literal":"A"}, {"literal":"I"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$105", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$106", "symbols": [{"literal":"U"}, {"literal":"P"}, {"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$106"]},
    {"name": "instruction$string$107", "symbols": [{"literal":"U"}, {"literal":"P"}, {"literal":"D"}, {"literal":"A"}, {"literal":"T"}, {"literal":"E"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$107", "__", "int"], "postprocess": single_param},
    {"name": "instruction$string$108", "symbols": [{"literal":"V"}, {"literal":"O"}, {"literal":"T"}, {"literal":"I"}, {"literal":"N"}, {"literal":"G"}, {"literal":"_"}, {"literal":"P"}, {"literal":"O"}, {"literal":"W"}, {"literal":"E"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$108"]},
    {"name": "instruction$string$109", "symbols": [{"literal":"X"}, {"literal":"O"}, {"literal":"R"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$109"]},
    {"name": "instruction$string$110", "symbols": [{"literal":"{"}, {"literal":"}"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "instruction", "symbols": ["instruction$string$110"]},
    {"name": "pushh$string$1", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pushh", "symbols": ["pushh$string$1", "__", "dqstring"], "postprocess": function(d) { return [ d[0], d[2] ] }},
    {"name": "pushh$string$2", "symbols": [{"literal":"s"}, {"literal":"t"}, {"literal":"r"}, {"literal":"i"}, {"literal":"n"}, {"literal":"g"}], "postprocess": function joiner(d) {return d.join('');}},
    {"name": "pushh", "symbols": ["pushh$string$2", "__", "sqstring"], "postprocess": function(d) { return [ d[0], d[2] ] }},
    {"name": "pushh", "symbols": ["type", "__", "int"], "postprocess": function(d) { return [ d[0], d[2] ] }}
]
  , ParserStart: "main"
}
if (typeof module !== 'undefined'&& typeof module.exports !== 'undefined') {
   module.exports = grammar;
} else {
   window.grammar = grammar;
}
})();
