name: "Parse test"

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install --save nearley
      - run: npm install -g nearley
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - uses: GuillaumeFalourd/clone-github-repo-action@v2
        with:
          owner: 'berkaycagir'
          repository: 'michelson-test-scripts'
          access-token: ${{ secrets.ACCESS_TOKEN }}
      - run: python3 michelson-test-scripts/test.py
