name: "Parse test"

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: 'npm'
      - run: npm install
      - run: npm test
      - run: npm install --save nearley
      - run: npm install -g nearley
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: cd test/
      - run: python3 test.py
